### ISSUE TITLE
Output Type Inconsistent 

### ISSUE THREAD

**Issue by pittmanriley** [ersilia-os/eos74bo#29]
Hi @GemmaTuron, I came across the same issue that we were having with eos6o0z, where the output sometimes is a list containing a float, while other times it is just a float. @samuelmaina fixed it with that model, so would you like me to fix it and submit a PR? 

For reference, I got this in the first output: 
`'output': {'outcome': [0.314]}}`

And this in the second output: 
`'output': {'outcome': 0.3140000104904175}}`

**Comment by GemmaTuron** [comment]
Yes, let's get this consistent
The output should be a float, since it is only one single value, thanks!

**Comment by pittmanriley** [comment]
@GemmaTuron Sounds good. I submitted the PR and it should work well now.
